export const SELECT_TOOL_ID = 'SELECT_TOOL_ID';
export const SELECT_DEFINITION_ID = 'SELECT_DEFINITION_ID';
export const UPDATE_PAINTING_STATE = 'UPDATE_PAINTING_STATE';
export const UPDATE_PLAYBACK_STATE = 'UPDATE_PLAYBACK_STATE';

export const UPSERT_ACTOR = 'UPSERT_ACTOR';
export const DELETE_ACTOR = 'DELETE_ACTOR';

export const UPSERT_CHARACTER = 'UPSERT_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
