export const SELECT_TOOL_ID = 'SELECT_TOOL_ID';
export const SELECT_DEFINITION_ID = 'SELECT_DEFINITION_ID';
export const UPDATE_PAINTING_STATE = 'UPDATE_PAINTING_STATE';
export const UPDATE_PLAYBACK_STATE = 'UPDATE_PLAYBACK_STATE';
export const UPDATE_KEYPICKER_STATE = 'UPDATE_KEYPICKER_STATE';
export const UPDATE_RECORDING_STATE = 'UPDATE_RECORDING_STATE';

export const UPSERT_ACTOR = 'UPSERT_ACTOR';
export const DELETE_ACTOR = 'DELETE_ACTOR';

export const UPSERT_CHARACTER = 'UPSERT_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';

export const ADVANCE_GAME_STATE = 'ADVANCE_GAME_STATE';
export const INPUT_FOR_GAME_STATE = 'INPUT_FOR_GAME_STATE';
